# Generated by Django 5.2.3 on 2025-06-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customerprofile_farmerprofile_delete_usercopy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='province',
            field=models.CharField(default='Bagmati', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='province',
            field=models.CharField(default='Bagmati', max_length=100, null=True),
        ),
    ]
