# Generated by Django 5.2.3 on 2025-07-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='province',
            field=models.CharField(choices=[('Koshi', 'Koshi'), ('Madhesh', 'Madhesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], default='Bagmati', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='province',
            field=models.CharField(choices=[('Koshi', 'Koshi'), ('Madhesh', 'Madhesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], default='Bagmati', max_length=100, null=True),
        ),
    ]
