# Generated by Django 5.2.3 on 2025-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
