# Generated by Django 5.2.3 on 2025-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='type',
            field=models.CharField(choices=[('Farming Tool', 'Farming Tool'), ('Machinery', 'Machinery'), ('Seed', 'Seed'), ('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
