# Generated by Django 5.2.3 on 2025-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryproduct_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='type',
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='category',
            field=models.CharField(choices=[('Machinery', 'Machinery'), ('Farming Tool', 'Farming Tool'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Seeds', 'Seeds'), ('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Grains', 'Grains'), ('Herbs', 'Herbs'), ('Dairy', 'Dairy'), ('Other', 'Other')], max_length=100),
        ),
    ]
