# Generated by Django 5.2.3 on 2025-07-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryproduct_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
