# Generated by Django 5.2.3 on 2025-07-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryproduct_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
