# Generated by Django 5.2.3 on 2025-07-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryreviewlike'),
        ('orders', '0002_order_orderitem'),
        ('products', '0003_productreview_dislikes_productreview_likes_and_more'),
        ('users', '0007_alter_customerprofile_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='inventory_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryproduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryproduct'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='users.farmerprofile'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
