# Generated by Django 5.2.3 on 2025-08-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method_order_payment_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
